name: Azure Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build and publish
      run: |
        dotnet build Kinodev.Functions.sln --configuration Release
        dotnet publish src/Kinodev.Functions.csproj --configuration Release --output ./publish
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: function-app
        path: ./publish
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://${{ vars.AZURE_FUNCTION_NAME }}.azurewebsites.net
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: function-app
        path: ./publish
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SERVICE_CONNECTION }}
        
    - name: Deploy to Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ vars.AZURE_FUNCTION_NAME }}
        package: './publish'
