name: Build Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - run: dotnet build Kinodev.Functions.sln --configuration Release
